package es.codeurjc.shopventory.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import es.codeurjc.shopventory.model.Product;

public interface ProductRepository extends JpaRepository<Product, Long> {

    Optional<Product> findBySku(String sku);

    boolean existsBySku(String sku);

    Page<Product> findByNameContainingIgnoreCaseOrDescriptionShortContainingIgnoreCase(
            String name, String description, Pageable pageable);

    Page<Product> findByCategoriesContaining(String category, Pageable pageable);

    @Query("SELECT p FROM ProductTable p WHERE p.stock <= p.minStockThreshold")
    Page<Product> findLowStockProducts(Pageable pageable);

    @Query("SELECT COUNT(p) FROM ProductTable p WHERE p.stock <= p.minStockThreshold")
    long countLowStockProducts();

    List<Product> findTop5ByOrderByStockDesc();

    @Query("SELECT c, COUNT(p) FROM ProductTable p JOIN p.categories c GROUP BY c")
    List<Object[]> findCategoryDistribution();

    Page<Product> findByProviderId(Long providerId, Pageable pageable);

    @Query("SELECT p.sku FROM ProductTable p WHERE p.sku LIKE 'AUTO-%'")
    List<String> findAutoGeneratedSkus();
}
