package es.codeurjc.shopventory.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import es.codeurjc.shopventory.model.Product;
import es.codeurjc.shopventory.model.Provider;

public interface ProductRepository extends JpaRepository<Product, Long> {

    Optional<Product> findBySku(String sku);

    boolean existsBySku(String sku);

    @Query("SELECT p FROM ProductTable p WHERE " +
           "LOWER(p.name) LIKE LOWER(CONCAT('%',:q,'%')) OR " +
           "LOWER(p.descriptionShort) LIKE LOWER(CONCAT('%',:q,'%')) OR " +
           "LOWER(p.sku) LIKE LOWER(CONCAT('%',:q,'%'))")
    Page<Product> searchByNameOrDescriptionOrSku(@Param("q") String q, Pageable pageable);

    Page<Product> findByCategoriesContaining(String category, Pageable pageable);

    @Query("SELECT p FROM ProductTable p WHERE p.stock <= p.minStockThreshold")
    Page<Product> findLowStockProducts(Pageable pageable);

    @Query("SELECT COUNT(p) FROM ProductTable p WHERE p.stock <= p.minStockThreshold")
    long countLowStockProducts();

    List<Product> findTop5ByOrderByStockDesc();

    List<Product> findTop5ByOrderByStockAsc();

    @Query("SELECT c, COUNT(p) FROM ProductTable p JOIN p.categories c GROUP BY c")
    List<Object[]> findCategoryDistribution();

    @Query("SELECT p FROM ProductTable p JOIN p.providers pr WHERE pr.id = :providerId")
    Page<Product> findByProviderId(@Param("providerId") Long providerId, Pageable pageable);

    long countByProvidersContaining(Provider provider);

    @Query("SELECT p.sku FROM ProductTable p WHERE p.sku LIKE 'AUTO-%'")
    List<String> findAutoGeneratedSkus();
}
